using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WebApi.shared.persistence.migrations
{
    /// <inheritdoc />
    public partial class AddProfessionalLocations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "ProfessionalLocations" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "ProfessionalId" integer NOT NULL,
                    "Name" character varying(150) NOT NULL,
                    "FormattedAddress" character varying(250) NULL,
                    "Street" character varying(150) NULL,
                    "StreetNumber" character varying(20) NULL,
                    "City" character varying(100) NULL,
                    "Province" character varying(100) NULL,
                    "PostalCode" character varying(20) NULL,
                    "Latitude" numeric(9,6) NULL,
                    "Longitude" numeric(9,6) NULL,
                    "ExternalPlaceId" character varying(250) NULL,
                    "ExternalProvider" character varying(50) NULL,
                    "Instructions" character varying(500) NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    CONSTRAINT "PK_ProfessionalLocations" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_ProfessionalLocations_People_ProfessionalId"
                        FOREIGN KEY ("ProfessionalId") REFERENCES "People" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_ProfessionalLocations_ProfessionalId"
                    ON "ProfessionalLocations" ("ProfessionalId");
                """
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ProfessionalLocations");
        }
    }
}
